-- PharmaTwin: batch_support_timeseries table - the 8 new process parameters
-- (Inlet Air Humidity, Exhaust Air Temperature, Filter Differential Pressure,
-- Shaker/Vibration Frequency, Product Bed Temperature, Chamber Differential
-- Pressure, AHU Damper Position, Compressed Air Pressure), one row per batch
-- per minute - same grain as the existing `batch_timeseries` table.
--
-- A separate table rather than adding columns to `batch_timeseries`, matching
-- how this project already keeps distinct concerns in their own tables (see
-- schema_alerts.sql) - `batch_timeseries` is a faithful mirror of the
-- original 4-parameter dataset, left untouched.
--
-- Generated by scripts/generate-support-parameters/generate_support_parameters.py
-- - synthetic/engineered data (same spirit as the rest of this dataset), not
-- measured, designed to be physically plausible for paracetamol fluid-bed
-- drying and correlated with the real Temperature/Flow Rate values already
-- in `batch_timeseries` for the same batch.

BEGIN;

CREATE TABLE batch_support_timeseries (
    batch_id                            text NOT NULL REFERENCES batches (batch_id) ON DELETE CASCADE,
    elapsed_minutes                      integer NOT NULL CHECK (elapsed_minutes >= 0),
    inlet_air_humidity_pct               double precision NOT NULL,
    exhaust_air_temp_c                   double precision NOT NULL,
    filter_differential_pressure_mbar    double precision NOT NULL,
    shaker_vibration_frequency_hz        double precision NOT NULL,
    product_bed_temp_c                   double precision NOT NULL,
    chamber_differential_pressure_mbar   double precision NOT NULL,
    ahu_damper_position_pct              double precision NOT NULL,
    compressed_air_pressure_bar          double precision NOT NULL,
    PRIMARY KEY (batch_id, elapsed_minutes)
);

CREATE INDEX idx_support_timeseries_elapsed ON batch_support_timeseries (elapsed_minutes);

COMMIT;
